const i18n={en:{yourPet:'YOUR PET',nextUp:'NEXT UP',upcoming:'UPCOMING',healthCare:'Health care',notes:'Notes',addReminder:'Add reminder',newReminder:'New reminder',type:'Type',name:'Name / note',date:'Date',repeat:'Repeat',saveReminder:'Save reminder',editPet:'Edit pet',petName:'Pet name',breed:'Breed',birthday:'Birthday',sex:'Sex',photo:'Photo',save:'Save',cancel:'Cancel',delete:'Delete',addNote:'Add a note',note:'Note',saveNote:'Save note',birthdayReminder:'Birthday reminder',female:'Female',male:'Male',home:'Home',records:'Records',health:'Health',pets:'Pets',weight:'Weight',latestWeight:'Latest entry',addWeight:'Add weight',careInfo:'Care information',vet:'Veterinarian',noVet:'No veterinarian saved',edit:'Edit',documents:'Documents & photos',reminderLead:'Reminder notice',myPets:'My pets',addPet:'Add pet',clinic:'Clinic name',phone:'Phone',address:'Address',emergency:'Emergency contact'},de:{yourPet:'DEIN HAUSTIER',nextUp:'ALS NÄCHSTES',upcoming:'BEVORSTEHEND',healthCare:'Gesundheit',notes:'Notizen',addReminder:'Erinnerung hinzufügen',newReminder:'Neue Erinnerung',type:'Art',name:'Name / Notiz',date:'Datum',repeat:'Wiederholung',saveReminder:'Erinnerung speichern',editPet:'Tier bearbeiten',petName:'Name des Tiers',breed:'Rasse',birthday:'Geburtstag',sex:'Geschlecht',photo:'Foto',save:'Speichern',cancel:'Abbrechen',delete:'Löschen',addNote:'Notiz hinzufügen',note:'Notiz',saveNote:'Notiz speichern',birthdayReminder:'Geburtstagserinnerung',female:'Weiblich',male:'Männlich',home:'Start',records:'Aufzeichnungen',health:'Gesundheit',pets:'Tiere',weight:'Gewicht',latestWeight:'Letzter Eintrag',addWeight:'Gewicht hinzufügen',careInfo:'Gesundheitsinfos',vet:'Tierarzt',noVet:'Kein Tierarzt gespeichert',edit:'Bearbeiten',documents:'Dokumente & Fotos',reminderLead:'Erinnerung vorher',myPets:'Meine Tiere',addPet:'Tier hinzufügen',clinic:'Name der Praxis',phone:'Telefon',address:'Adresse',emergency:'Notfallkontakt'}};
const initial={lang:'en',pet:{name:'Milo',breed:'Golden Retriever',birthday:'2022-05-14',sex:'male',photo:''},notes:[],tasks:[{id:1,type:'worm',name:'Worm treatment',date:'2026-08-17',repeat:3},{id:2,type:'vaccine',name:'Leptospirosis vaccine',date:'2026-10-04',repeat:12},{id:3,type:'checkup',name:'Annual vet check-up',date:'2027-02-10',repeat:12}]};
let state=JSON.parse(localStorage.getItem('pawplan')||'null')||initial;
if(!Array.isArray(state.pets)||!state.pets.length){const legacy=state.pet||initial.pet;state.pets=[{...legacy,id:'milo',weights:[],vet:{},documents:[],lead:7}];state.activePet='milo';(state.tasks||[]).forEach(x=>x.petId='milo');state.notes??=[];state.notes.forEach(x=>x.petId='milo');delete state.pet}if(!state.pets.some(p=>p.id===state.activePet))state.activePet=state.pets[0].id;state.tasks??=[];state.notes??=[];
Object.defineProperty(state,'pet',{enumerable:false,get(){return state.pets.find(p=>p.id===state.activePet)},set(value){const i=state.pets.findIndex(p=>p.id===state.activePet);state.pets[i]={...state.pets[i],...value}}});
state.pet.birthday??='';state.pet.sex??='';state.pet.photo??='';state.pet.weights??=[];state.pet.vet??={};state.pet.documents??=[];state.pet.lead??=7;
const $=id=>document.getElementById(id),icons={worm:'💊',vaccine:'💉',medicine:'🩹',checkup:'🩺',grooming:'✂️'};const save=()=>localStorage.setItem('pawplan',JSON.stringify(state));
function formatDate(v){return new Intl.DateTimeFormat(state.lang==='de'?'de-DE':'en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(v+'T12:00:00'))}
function repeatLabel(m){const y=m/12;return state.lang==='de'?(m<12?(m===1?'Jeden Monat':`Alle ${m} Monate`):(y===1?'Jedes Jahr':`Alle ${y} Jahre`)):(m<12?(m===1?'Every month':`Every ${m} months`):(y===1?'Every year':`Every ${y} years`))}
function nextBirthday(date){const b=new Date(date+'T12:00:00'),n=new Date();b.setFullYear(n.getFullYear());if(b<n)b.setFullYear(n.getFullYear()+1);return b.toISOString().slice(0,10)}
function ageLabel(date){if(!date)return '';const b=new Date(date+'T12:00:00'),n=new Date();let a=n.getFullYear()-b.getFullYear();if(n<new Date(n.getFullYear(),b.getMonth(),b.getDate()))a--;return state.lang==='de'?`${a} Jahre`:`${a} years`}
function render(){const t=i18n[state.lang];document.documentElement.lang=state.lang;$('languageButton').textContent=state.lang.toUpperCase();document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=t[e.dataset.i18n]);$('petName').textContent=state.pet.name;$('petAvatar').innerHTML=state.pet.photo?`<img src="${state.pet.photo}" alt="${state.pet.name}">`:'🐶';$('petMeta').textContent=[state.pet.breed,ageLabel(state.pet.birthday),state.pet.sex?t[state.pet.sex]:null].filter(Boolean).join(' · ');const tasks=state.tasks.filter(x=>x.petId===state.activePet);if(state.pet.birthday)tasks.push({id:'birthday',type:'birthday',name:t.birthdayReminder,date:nextBirthday(state.pet.birthday),repeat:12});tasks.sort((a,b)=>a.date.localeCompare(b.date));const f=tasks[0];if(f){$('nextTitle').textContent=f.name;$('nextDate').textContent=formatDate(f.date);const d=new Date(f.date+'T12:00:00');$('nextDay').textContent=d.getDate();$('nextMonth').textContent=new Intl.DateTimeFormat(state.lang==='de'?'de-DE':'en-US',{month:'short'}).format(d).toUpperCase()}$('taskList').innerHTML=tasks.map(x=>`<article class="task"><div class="icon">${x.type==='birthday'?'🎂':icons[x.type]}</div><div class="task-copy"><h3>${x.name}</h3><p>${x.repeat?repeatLabel(x.repeat):state.lang==='de'?'Einmalig':'One time'}</p></div><div class="date"><b>${formatDate(x.date)}</b><span>${x.repeat?'↻':''}</span></div>${x.id==='birthday'?'':`<button type="button" class="delete-button" data-delete-task="${x.id}" aria-label="${t.delete}" title="${t.delete}">×</button>`}</article>`).join('');renderExtras(t)}
function renderExtras(t){const w=[...state.pet.weights].sort((a,b)=>b.date.localeCompare(a.date));$('latestWeight').textContent=w.length?`${w[0].value} kg`:'—';$('weightList').innerHTML=w.map(x=>`<div class="mini-item"><span>${formatDate(x.date)}</span><b>${x.value} kg</b></div>`).join('')||'<p>—</p>';const v=state.pet.vet;$('vetDisplay').textContent=v.clinic?[v.clinic,v.phone,v.address].filter(Boolean).join(' · '):t.noVet;$('leadSelect').value=state.pet.lead;$('documentCount').textContent=`${state.pet.documents.length} ${t.documents.toLowerCase()}`;$('documentList').innerHTML=state.pet.documents.map(x=>`<div class="mini-item"><span>${x.data?`<img class="doc-thumb" src="${x.data}" alt="">`: '📎'} ${x.name}</span></div>`).join('');$('petsList').innerHTML=state.pets.map(p=>`<button class="pet-choice ${p.id===state.activePet?'active':''}" data-pet="${p.id}"><span>${p.photo?'📷':'🐾'} ${p.name}</span><span>${p.breed||''}</span></button>`).join('')}
$('languageButton').onclick=()=>{state.lang=state.lang==='en'?'de':'en';save();render()};$('openAdd').onclick=()=>{$('taskDate').value=new Date().toISOString().slice(0,10);$('taskDialog').showModal()};
$('taskForm').addEventListener('submit',e=>{if(e.submitter.value==='cancel')return;e.preventDefault();state.tasks.push({id:Date.now(),petId:state.activePet,type:$('taskType').value,name:$('taskName').value,date:$('taskDate').value,repeat:+$('taskRepeat').value});save();render();$('taskDialog').close()});
$('taskList').onclick=e=>{const button=e.target.closest('[data-delete-task]');if(!button)return;state.tasks=state.tasks.filter(x=>String(x.id)!==button.dataset.deleteTask);save();render()};
$('editPet').onclick=()=>{$('petNameInput').value=state.pet.name;$('breedInput').value=state.pet.breed;$('birthdayInput').value=state.pet.birthday;$('sexInput').value=state.pet.sex;$('photoInput').value='';$('petDialog').showModal()};
$('photoInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const c=document.createElement('canvas'),scale=Math.min(1,320/Math.max(img.width,img.height));c.width=img.width*scale;c.height=img.height*scale;c.getContext('2d').drawImage(img,0,0,c.width,c.height);state.pet.photo=c.toDataURL('image/jpeg',.82);$('petAvatar').innerHTML=`<img src="${state.pet.photo}" alt="">`};img.src=reader.result};reader.readAsDataURL(file)};
$('petForm').addEventListener('submit',e=>{if(e.submitter.value==='cancel')return;e.preventDefault();state.pet={...state.pet,name:$('petNameInput').value,breed:$('breedInput').value,birthday:$('birthdayInput').value,sex:$('sexInput').value};save();render();$('petDialog').close()});
$('viewHistory').onclick=$('openNotes').onclick=()=>{$('noteDate').value=new Date().toISOString().slice(0,10);const n=state.notes.filter(x=>x.petId===state.activePet).sort((a,b)=>b.date.localeCompare(a.date));$('notesList').innerHTML=n.length?n.map(x=>`<article class="note-item"><b>${formatDate(x.date)}</b><p>${x.text}</p></article>`).join(''):`<p>${state.lang==='de'?'Noch keine Notizen.':'No notes yet.'}</p>`;$('notesDialog').showModal()};
$('noteForm').addEventListener('submit',e=>{if(e.submitter.value==='cancel')return;e.preventDefault();state.notes.push({id:Date.now(),petId:state.activePet,date:$('noteDate').value,text:$('noteText').value});save();render();$('notesDialog').close()});
$('openWeight').onclick=()=>{$('weightDate').value=new Date().toISOString().slice(0,10);$('weightDialog').showModal()};$('weightForm').addEventListener('submit',e=>{if(e.submitter.value==='cancel')return;e.preventDefault();state.pet.weights.push({date:$('weightDate').value,value:$('weightInput').value});save();render();$('weightDialog').close()});
$('openVet').onclick=()=>{const v=state.pet.vet;$('vetClinic').value=v.clinic||'';$('vetPhone').value=v.phone||'';$('vetAddress').value=v.address||'';$('vetEmergency').value=v.emergency||'';$('vetDialog').showModal()};$('vetForm').addEventListener('submit',e=>{if(e.submitter.value==='cancel')return;e.preventDefault();state.pet.vet={clinic:$('vetClinic').value,phone:$('vetPhone').value,address:$('vetAddress').value,emergency:$('vetEmergency').value};save();render();$('vetDialog').close()});
$('leadSelect').onchange=e=>{state.pet.lead=+e.target.value;save()};$('documentInput').onchange=e=>{[...e.target.files].forEach(f=>{if(!f.type.startsWith('image/')){state.pet.documents.push({id:Date.now()+f.name,name:f.name});save();render();return}const r=new FileReader();r.onload=()=>{state.pet.documents.push({id:Date.now()+f.name,name:f.name,data:r.result});save();render()};r.readAsDataURL(f)});e.target.value=''};
$('addPet').onclick=()=>{state.pets.push({id:`pet-${Date.now()}`,name:'New pet',breed:'',birthday:'',sex:'',photo:'',weights:[],vet:{},documents:[],lead:7});state.activePet=state.pets.at(-1).id;save();render();$('editPet').click()};$('petsList').onclick=e=>{const b=e.target.closest('[data-pet]');if(b){state.activePet=b.dataset.pet;save();render();document.querySelector('[data-tab="home"]').click()}};
document.querySelector('nav').onclick=e=>{const b=e.target.closest('[data-tab]');if(!b)return;document.querySelectorAll('[data-screen]').forEach(s=>s.hidden=s.dataset.screen!==b.dataset.tab);document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b))};
document.querySelectorAll('dialog').forEach(dialog=>{dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>dialog.close())});render();
